name: CI

on: [push, pull_request]

jobs:
  default:
    name: Build and Test on ${{ matrix.os }} with Node.js ${{ matrix.node }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        node:
          - 10
          - 14
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node }}
      - name: Get yarn
        run: |
          curl -o- -L https://yarnpkg.com/install.sh | bash
          export PATH="$HOME/.yarn/bin:$PATH"
      - name: Get yarn cache
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Set yarn cache
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-${{ matrix.node }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node }}-yarn-
      - name: Install
        run: yarn --frozen-lockfile
        env:
          CI: 'true'
      - name: Test
        run: yarn test
      # To do: macos isnâ€™t used anymore
      - name: Publish CI tag to npm
        if: matrix.node == 12 && matrix.os == 'macOS-latest' && github.event_name == 'push' && github.ref	== 'refs/heads/master'
        run: |
          npm set //registry.npmjs.org/:_authToken $NPM_AUTH_TOKEN
          yarn publish-ci
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
