name: CI

on: [push, pull_request]

jobs:
  default:
    name: Build and Test on ${{ matrix.os }} with Node.js ${{ matrix.node }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        node:
          - 10
          - 14
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node }}
      - name: Install
        run: yarn --frozen-lockfile
        env:
          CI: 'true'
      - name: Test (max)
        if: contains(matrix.os, 'ubuntu')
        run: yarn test
      - name: Test (min)
        if: contains(matrix.os, 'windows')
        run: yarn build && yarn test-mini
      # To do: macos isnâ€™t used anymore
      - name: Publish CI tag to npm
        if: matrix.node == 12 && matrix.os == 'macOS-latest' && github.event_name == 'push' && github.ref	== 'refs/heads/master'
        run: |
          npm set //registry.npmjs.org/:_authToken $NPM_AUTH_TOKEN
          yarn publish-ci
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
